#ifndef ERRORS_H
#define ERRORS_H

typedef enum {
    ERR_MISSING_SEMICOLON,
    ERR_MISSING_IDENTIFIER,
    ERR_MISSING_CLOSING_PAREN,
    ERR_MISSING_OPENING_PAREN,
    ERR_MISSING_CLOSING_BRACE,
    ERR_MISSING_OPENING_BRACE,
    ERR_MISSING_CLOSING_BRACKET,
    ERR_MISSING_FUNC_NAME,
    ERR_MISSING_PARAM_VAR,
    ERR_MISSING_CONDITION,
    ERR_INCOMPLETE_EXPRESSION,
    ERR_UNEXPECTED_TOKEN,
    ERR_UNDECLARED,
    ERR_GENERIC
} ErrorType;

void report_error(ErrorType type, int line, int col, const char *token);

#endif